-- Las cuentas de prospecto no son usuarios internos del CRM. Se enlazan a
-- Supabase Auth para que una persona pueda consultar únicamente sus novedades.
-- La secuencia puede haberse quedado detrás de filas creadas manualmente.
select setval(
  pg_get_serial_sequence('public.profiles', 'id'),
  coalesce((select max(id) from public.profiles), 1),
  true
);

insert into public.profiles (nombre, descripcion)
select 'prospect', 'Prospecto con acceso únicamente a su cuenta de seguimiento.'
where not exists (
  select 1 from public.profiles where nombre = 'prospect'
);

-- Conserva las asignaciones existentes. Solo asigna los leads históricos que
-- todavía no tenían responsable al primer ejecutivo activo disponible.
with active_executive as (
  select u.id
  from public.users u
  join public.profiles p on p.id = u.profile_id
  where p.nombre = 'executive' and u.is_active = true
  order by u.id
  limit 1
)
update public.leads
set assigned_user_id = (select id from active_executive)
where assigned_user_id is null
  and exists (select 1 from active_executive);

create table if not exists public.prospect_accounts (
  id uuid primary key default gen_random_uuid(),
  lead_id uuid not null unique references public.leads(id) on delete cascade,
  auth_user_id uuid not null unique references auth.users(id) on delete cascade,
  email text not null,
  status text not null default 'pending_verification'
    check (status in ('pending_verification', 'active', 'disabled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Son mensajes deliberadamente publicados para el prospecto. No se reutilizan
-- notas internas ni acciones comerciales, que pueden contener contexto privado.
create table if not exists public.client_updates (
  id bigint generated by default as identity primary key,
  lead_id uuid not null references public.leads(id) on delete cascade,
  created_by uuid references public.users(id) on delete set null,
  message text not null check (char_length(message) between 1 and 2000),
  created_at timestamptz not null default now()
);

create index if not exists prospect_accounts_lead_id_idx on public.prospect_accounts (lead_id);
create index if not exists client_updates_lead_id_idx on public.client_updates (lead_id, created_at desc);

alter table public.prospect_accounts enable row level security;
alter table public.client_updates enable row level security;

-- La aplicación usa rutas de servidor que validan la identidad antes de leer o
-- escribir. No se expone acceso directo desde el navegador a estas tablas.
grant select, insert, update on table public.prospect_accounts to service_role;
grant select, insert, update on table public.client_updates to service_role;
grant usage, select on sequence public.client_updates_id_seq to service_role;
